export const PROGRAM_ORGANIZER_TYPE = "PROGRAM_ORGANIZER_TYPE";

export const TIME_FORMAT = "TIME_FORMAT";

export const USER_ROLE = "USER_ROLE";

export const PROGRAM_CATEGORY = "PROGRAM_CATEGORY";

export const CERTIFICATION_TYPE = "CERTIFICATION_TYPE";

export const VISIBILITY = "VISIBILITY";

export const PROGRAM_STATUS = "PROGRAM_STATUS";

export const COURSE_ACCOUNTING_STATUS = "COURSE_ACCOUNTING_STATUS";
