export const PROGRAM_ORGANIZER_TYPE = "PROGRAM_ORGANIZER_TYPE";

export const TIME_FORMAT = "TIME_FORMAT";


export const PARTICIPANT_PAYMENT_STATUS = "PARTICIPANT_PAYMENT_STATUS";

export const PARTICIPANT_ATTENDANCE_STATUS = "PARTICIPANT_ATTENDANCE_STATUS";


