export const PROGRAM_ORGANIZER_TYPE = "PROGRAM_ORGANIZER_TYPE";

export const TIME_FORMAT = "TIME_FORMAT";

export const PROGRAM_STATUS = "PROGRAM_STATUS"

export const USER_ROLE = "USER_ROLE"

export const COURSE_ACCOUNTING_STATUS = "COURSE_ACCOUNTING_STATUS"

